In [1]:
import tensorflow as tf


In [2]:
w = tf.Variable([[5.0]])
with tf.GradientTape() as tape:
  loss = w**3


In [3]:
tape.gradient(loss, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[75.]], dtype=float32)>

Chain Rule Unleashed

In [4]:
x = tf.ones((2,2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [5]:
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y = tf.reduce_sum(x)
  z = tf.square(y)

In [6]:
dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


Double Derivative

In [7]:
x = tf.Variable(3.0)

In [8]:
with tf.GradientTape() as tape2:
  with tf.GradientTape() as tape1:
    y = 2*(x**3) + x**2 + 1
  dy_dx = tape1.gradient(y, x)
d2y_dx = tape2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx)

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(38.0, shape=(), dtype=float32)
